import { useState } from 'react';
import { Check, ChevronDown, Play, Plus, Target, Trash2, X } from 'lucide-react';
import { api, json } from '../api.js';
import '../curriculum.css';

export default function CurriculumPanel({data,onClose,onChange}){
  const [moduleTitle,setModuleTitle]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const addModule=async e=>{e.preventDefault();setBusy(true);setError('');try{await api(`/admin/courses/${data.course.id}/modules`,json('POST',{title:moduleTitle,position:data.modules.length}));setModuleTitle('');await onChange();}catch(e){setError(e.message);}finally{setBusy(false);}};
  const addLesson=async(e,module)=>{e.preventDefault();const form=e.currentTarget;setError('');try{await api(`/admin/modules/${module.id}/lessons`,json('POST',{title:form.title.value,description:form.description.value,durationMinutes:Number(form.duration.value)||10,videoUrl:form.video.value||null,position:module.lessons.length}));form.reset();await onChange();}catch(e){setError(e.message);}};
  const editLesson=async lesson=>{const title=window.prompt('Lesson title',lesson.title);if(!title)return;try{await api(`/admin/lessons/${lesson.id}`,json('PUT',{title}));await onChange();}catch(e){setError(e.message);}};
  const deleteLesson=async lesson=>{if(!window.confirm(`Delete lesson “${lesson.title}”?`))return;try{await api(`/admin/lessons/${lesson.id}`,{method:'DELETE'});await onChange();}catch(e){setError(e.message);}};
  const deleteModule=async module=>{if(!window.confirm(`Delete “${module.title}” and its lessons?`))return;try{await api(`/admin/modules/${module.id}`,{method:'DELETE'});await onChange();}catch(e){setError(e.message);}};
  const addQuiz=async module=>{const title=window.prompt('Knowledge check title',`${module.title} knowledge check`);if(!title)return;try{await api(`/admin/modules/${module.id}/quizzes`,json('POST',{title}));await onChange();}catch(e){setError(e.message);}};
  const addQuizQuestion=async module=>{const prompt=window.prompt('Question text');if(!prompt)return;const options=[0,1,2,3].map(i=>window.prompt(`Option ${String.fromCharCode(65+i)}`)||'');if(options.some(x=>!x.trim()))return;const correctIndex=Number(window.prompt('Correct option number (1–4)','1'))-1;if(correctIndex<0||correctIndex>3)return;try{await api(`/admin/quizzes/${module.quiz_id}/questions`,json('POST',{prompt,options,correctIndex,explanation:window.prompt('Explanation (optional)')||''}));}catch(e){setError(e.message);}};
  return <section className="curriculum-manager"><div className="curriculum-manager-head"><div><span className="eyebrow">COURSE BUILDER</span><h2>{data.course.title}</h2><p>Add and organise course modules, lessons and knowledge checks.</p></div><button className="icon-button" onClick={onClose} aria-label="Close curriculum"><X size={17}/></button></div>{error&&<div className="form-error">{error}</div>}<form className="curriculum-module-form" onSubmit={addModule}><input required minLength={2} value={moduleTitle} onChange={e=>setModuleTitle(e.target.value)} placeholder="Name a new module"/><button className="button button-dark button-small" disabled={busy}><Plus size={14}/> Add module</button></form><div className="curriculum-admin-modules">{data.modules.map((m,i)=><article className="curriculum-admin-module" key={m.id}><div className="curriculum-admin-title"><span>{String(i+1).padStart(2,'0')}</span><strong>{m.title}</strong><small>{m.lessons.length} lessons</small><button className="delete-action" onClick={()=>deleteModule(m)} aria-label="Delete module"><Trash2 size={14}/></button></div>{m.lessons.map(l=><div className="curriculum-admin-lesson" key={l.id}><Play size={13}/><span>{l.title}</span><small>{l.duration_minutes} min</small><button onClick={()=>editLesson(l)}>Edit</button><button className="delete-action" onClick={()=>deleteLesson(l)} aria-label="Delete lesson"><Trash2 size={13}/></button></div>)}<details className="curriculum-lesson-form"><summary><Plus size={13}/> Add a lesson <ChevronDown size={13}/></summary><form onSubmit={e=>addLesson(e,m)}><input name="title" required minLength={2} placeholder="Lesson title"/><input name="description" placeholder="Short lesson description"/><div><input name="duration" type="number" min="1" defaultValue="10" aria-label="Duration in minutes"/><input name="video" type="url" placeholder="YouTube embed URL (optional)"/></div><button className="button button-outline button-small">Save lesson <Check size={13}/></button></form></details><div className="curriculum-admin-quiz">{m.quiz_id?<><span><Target size={14}/>{m.quiz_title||'Module quiz'}</span><button onClick={()=>addQuizQuestion(m)}>Add quiz question <Plus size={12}/></button></>:<button onClick={()=>addQuiz(m)}><Plus size={13}/> Add a module quiz</button>}</div></article>)}{!data.modules.length&&<p className="empty-copy">Start the learning path by adding its first module.</p>}</div></section>;
}
